trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_CONTAINER_APP_NAME: 'building33-mock-api-iac'
  RESOURCE_GROUP: 'Gateway-Resources-IAC'
  DOCKER_IMAGE: 'attonbomb/building33mockapi'  # Replace with your Docker Hub image path
  AZURE_SUBSCRIPTION: 'Gateway-Resources-IAC-MI-Conn-2'
steps:
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: 'attonbomb-DockerHub-SC'
  
  # Set the Azure subscription based on the branch
  - script: |
      echo "Determining Azure subscription...$(Build.SourceBranchName)"
      if [ "$(Build.SourceBranchName)" = "development" ]; then
        echo "##vso[task.setvariable variable=AZURE_SUBSCRIPTION]Dev-Gateway-Resources-MS"
      else
        echo "##vso[task.setvariable variable=AZURE_SUBSCRIPTION]Gateway-Resources-IAC-MI-Conn-2"
      fi
    displayName: 'Set Azure Subscription to $(AZURE_SUBSCRIPTION)'
  
  # Force a restart of the Azure Container App
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -x
        echo "Restarting Azure Container App with new configuration"
        echo "Updating Azure Container App. The latest image version is ======= $(DOCKER_IMAGE_VERSION)"
        # Update the container image if applicable
        az containerapp update \
          --name building33-mock-api-iac \
          --resource-group Gateway-IAC-Resources \
          --image $(DOCKER_IMAGE):$(DOCKER_IMAGE_VERSION) \
          --query "[].properties.provisioningState"
        
        # Restart the app
        az containerapp revision restart \
          --name building33-mock-api-iac \
          --resource-group Gateway-IAC-Resources \
          --revision building33-mock-api-iac--t8pcudb
        
        echo "Global Integration API Container App updated successfully for Azure Subscription $(AZURE_SUBSCRIPTION)"

