trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_CONTAINER_APP_NAME: 'building33-mock-api-iac'
  RESOURCE_GROUP: 'Gateway-Resources-IAC'
  DOCKER_IMAGE: 'attonbomb/building33mockapi'  # Replace with your Docker Hub image path
  AZURE_SUBSCRIPTION: 'Gateway-Resources-IAC-MI-Conn-2'
steps:
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: 'attonbomb-DockerHub-SC'
  
  # Set the Azure subscription based on the branch
  - script: |
      echo "Determining Azure subscription...$(Build.SourceBranchName)"
      if [ "$(Build.SourceBranchName)" = "development" ]; then
        echo "##vso[task.setvariable variable=AZURE_SUBSCRIPTION]Dev-Gateway-Resources-MS"
      else
        echo "##vso[task.setvariable variable=AZURE_SUBSCRIPTION]Gateway-Resources-IAC-MI-Conn-2"
      fi
    displayName: 'Set Azure Subscription to $(AZURE_SUBSCRIPTION)'

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Using a different syntax ===== ${{variables['DOCKER_IMAGE_VERSION']}}"
        echo "Updating Azure Container App. The latest image version is ======= $(DOCKER_IMAGE_VERSION)"
        az config set extension.use_dynamic_install=yes_without_prompt
        
        # Update the Azure Container App to pull the latest image
        az containerapp deploy \
          --name building33-mock-api-iac
          --resource-group Gateway-IAC-Resources
          --image $(DOCKER_IMAGE):$(DOCKER_IMAGE_VERSION)
          --registry-server hub.docker.com

        echo "Global Integration API Container App updated successfully for Azure Subscription $(AZURE_SUBSCRIPTION)"
  
  # Force a restart of the Azure Container App
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(AZURE_SUBSCRIPTION)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Restarting Azure Container App to apply changes"
        az containerapp revision restart \
          --name building33-mock-api-iac \
          --resource-group Gateway-IAC-Resources

        echo "Azure Container App restarted successfully"

